# Generated by Django 3.0.6 on 2020-05-29 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
